# Generated by Django 5.0.4 on 2024-05-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("slug", models.CharField(max_length=100, verbose_name="Slug")),
                (
                    "text",
                    models.TextField(blank=True, null=True, verbose_name="Содержание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/photo",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                (
                    "public",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Признак публикации",
                    ),
                ),
                ("views", models.IntegerField(verbose_name="Просмотры")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
