# Generated by Django 5.0.4 on 2024-05-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="public",
        ),
    ]
