# Generated by Django 5.0.4 on 2024-05-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blog_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="public",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
