# Generated by Django 5.0.4 on 2024-05-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="public",
            field=models.BooleanField(default=False, verbose_name="Публикация"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
