# Generated by Django 5.0.4 on 2024-05-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_public_alter_blog_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
